apiVersion: v1
kind: Endpoints
metadata:
  name: kubedb
subsets:
- addresses:
  - ip: 172.16.100.60
  ports:
  - name: app
    port: 3306
    protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: kubedb
spec:
  ports:
  - name: app
    port: 3306
    protocol: TCP
    targetPort: 3306
  clusterIP: None
  type: ClusterIP

--- 

apiVersion: v1
data:
  password: ZnVrbzA5cGhzdXJ4aG8=
kind: Secret
metadata:
  creationTimestamp: null
  name: mysql-pass

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypterio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypterio
  template:
    metadata:
      labels:
        app: crypterio
    spec:
      containers:
      - name: crypterio
        image: virtapp/crypterio:latest
        resources: {}
        ports:
        - containerPort: 80
        env:
            - name: WORDPRESS_DB_HOST
              value: kubedb
            - name: WORDPRESS_DB_NAME
              value: crypterio
            - name: WORDPRESS_DB_USER
              value: root
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
      restartPolicy: Always
      nodeSelector: {}

---

apiVersion: v1
kind: Service
metadata:
  name: crypterio
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: crypterio

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-route-crypterio
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route-crypterio"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - crypterio.co
      secretName: crypterio-tls
  rules:
    - host: crypterio.co
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: crypterio
                port:
                  number: 80
